# Generated by Django 5.0.3 on 2024-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink',
            new_name='drink_name',
        ),
        migrations.AddField(
            model_name='drinks',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
