# Generated by Django 5.0.3 on 2024-03-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
